name: CI

on:
  pull_request:
    branches:
      - main

  workflow_dispatch:

jobs:
  frontend:
    name: Frontend Checks
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: pastry-recipes/client

    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Setup Node.js
        uses: actions/setup-node@v5
        with:
          node-version: 22
          cache: npm
          cache-dependency-path: pastry-recipes/client/package-lock.json

      - name: Install dependencies
        run: npm ci

      - name: Run ESLint
        run: npm run lint

      - name: Build frontend
        run: npm run build

  backend:
    name: Backend Checks
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: pastry-recipes/server

    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Setup Node.js
        uses: actions/setup-node@v5
        with:
          node-version: 22
          cache: npm
          cache-dependency-path: pastry-recipes/client/package-lock.json

      - name: Install dependencies
        run: npm ci